### ISSUE TITLE
Simple misspelling

### ISSUE THREAD

**Issue by bchmura** [panglesd/slipshow-vscode#2]
Super low priority

Presentations suck - I've always hated powerpoint for a lot of the reasons you talk about.  Long winded way of saying thank you for pushing the options and providing this.  I do most of my work in Obsidian, so porting and doing this is so easy.

Anyway, In VSCode when you preview the Slipshow a tab opens up.  The text on that tab says SLIPHOW not SLIPSHOW

This renders it literally unusable.  just killing, no impact but figure I would mention it with the thank you!

**Comment by panglesd** [comment]
Thank you for the kind words! I'm really glad it's helpful to others!

The typo is fixed in 0bf5078. It'll be released when I have fixed #1 (which is ongoing work!).
